# Generated by Django 4.1 on 2022-08-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspi', '0002_alter_event_id_alter_eventoftheweek_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='prepairation_time',
            new_name='preparation_time',
        ),
    ]
