# Generated by Django 4.1 on 2022-08-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspi', '0003_rename_prepairation_time_event_preparation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqrating',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='message',
            name='event',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.DeleteModel(
            name='FaqRating',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageType',
        ),
    ]
