# Generated by Django 4.1 on 2022-08-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspi', '0004_remove_faqrating_faq_remove_message_event_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Activity',
        ),
    ]
