# Generated by Django 4.0.4 on 2022-09-21 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0008_travelattributev2'),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('scout_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('address_supplement', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('phone_number_verified', models.BooleanField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_verified', models.BooleanField(default=0)),
                ('bundespost', models.CharField(choices=[('nothing', 'Keine Bundespost'), ('digital', 'Nur Digital'), ('digital_post', 'Digital und Post'), ('post', 'Nur per Post')], default='nothing', max_length=13)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Männlich'), ('F', 'Weiblich'), ('D', 'Divers'), ('N', 'Keine Angabe')], default='N', max_length=1)),
                ('active', models.BooleanField(default=False)),
                ('person_verified', models.BooleanField(default=False)),
                ('leader', models.CharField(choices=[('N', 'Kein Amt'), ('StaFue', 'Stammesführung'), ('SiFue', 'Sippenführung'), ('RoFue', 'Roverrundenführung'), ('MeuFue', 'Meutenführung')], default='N', max_length=6)),
                ('scout_level', models.CharField(choices=[('N', 'Unbekannt'), ('W', 'Wölfling'), ('S', 'Sippling'), ('R', 'Rover_Innen')], default='N', max_length=6)),
                ('created_by', models.ManyToManyField(related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('eat_habits', models.ManyToManyField(blank=True, to='basic.eathabit')),
                ('scout_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.scouthierarchy')),
                ('tags', models.ManyToManyField(blank=True, to='basic.abstractattribute')),
                ('zip_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.zipcode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userextended',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.person'),
        ),
    ]
