# Generated by Django 3.2.9 on 2021-11-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userextended_scout_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='dsgvo_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextended',
            name='successfull_initialised',
            field=models.BooleanField(default=False),
        ),
    ]
