# Generated by Django 4.0.3 on 2022-03-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='email_notifaction',
            field=models.CharField(choices=[('Full', 'Alles'), ('Daily', 'täglich'), ('Weekly', 'Wöchentlich'), ('Important', 'Nur wichtiges')], default='Full', max_length=10),
        ),
    ]
