# Generated by Django 4.0.1 on 2022-01-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='email_notifaction',
            field=models.CharField(choices=[('Full', 'Full'), ('Daily', 'Daily'), ('Important', 'Important')], default='Full', max_length=10),
        ),
        migrations.AddField(
            model_name='userextended',
            name='sms_notifcation',
            field=models.BooleanField(default=True),
        ),
    ]
