# Generated by Django 4.0.2 on 2022-02-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_alter_scouthierarchy_level_and_more'),
        ('authentication', '0003_userextended_email_notifaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='scout_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.scouthierarchy'),
        ),
    ]
