# Generated by Django 4.0.2 on 2022-02-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_alter_scouthierarchy_level_and_more'),
        ('authentication', '0004_alter_userextended_scout_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='scout_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.scouthierarchy'),
        ),
    ]
