# Generated by Django 4.0.4 on 2022-10-13 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_alter_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='owned_by',
            field=models.ManyToManyField(related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_by',
        ),
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Männlich'), ('F', 'Weiblich'), ('D', 'Divers'), ('N', 'Keine Angabe')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='leader',
            field=models.CharField(choices=[('N', 'Kein Amt'), ('BuFue', 'Bundesführung'), ('RinFue', 'Ringführung'), ('StaFue', 'Stammesführung'), ('SiFue', 'Sippenführung'), ('RoFue', 'Roverrundenführung'), ('MeuFue', 'Meutenführung')], default='N', max_length=6),
        ),
    ]
