# Generated by Django 4.1.2 on 2022-10-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_person_owned_by_remove_person_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='leader',
            field=models.CharField(choices=[('N', 'Kein Amt'), ('DPVFue', 'DPV-Führung'), ('BuFue', 'Bundesführung'), ('RinFue', 'Ringführung'), ('StaFue', 'Stammesführung'), ('SiFue', 'Sippenführung'), ('RoFue', 'Roverrundenführung'), ('MeuFue', 'Meutenführung')], default='N', max_length=6),
        ),
    ]
