# Generated by Django 4.0.3 on 2022-03-19 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('de5a23d3-a482-4eb8-b8e4-29209449d872'), primary_key=True, serialize=False),
        ),
    ]
