# Generated by Django 4.0.3 on 2022-03-31 21:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='tags',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.registration'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
