# Generated by Django 4.0.3 on 2022-03-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_eathabit'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationparticipant',
            name='eat_habit',
            field=models.ManyToManyField(to='basic.eathabit'),
        ),
    ]
