# Generated by Django 4.0.3 on 2022-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_alter_eathabit_name'),
        ('event', '0002_registrationparticipant_eat_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationparticipant',
            name='eat_habit',
            field=models.ManyToManyField(blank=True, to='basic.eathabit'),
        ),
    ]
