# Generated by Django 4.0.2 on 2022-03-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
        ('event', '0002_alter_registrationparticipant_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationparticipant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='basic.AbstractAttribute'),
        ),
    ]
