# Generated by Django 4.0.3 on 2022-03-25 08:52

import backend.storage_backends
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_emailpictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPicture',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.ImageField(storage=backend.storage_backends.PublicMediaStorage(), upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EmailPictures',
        ),
        migrations.AddField(
            model_name='email',
            name='attachments',
            field=models.ManyToManyField(to='event.emailattachment'),
        ),
    ]
