# Generated by Django 4.0.2 on 2022-03-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_alter_eathabit_name'),
        ('event', '0003_alter_registrationparticipant_eat_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingoption',
            name='tags',
            field=models.ManyToManyField(blank=True, to='basic.Tag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_planer_modules',
            field=models.ManyToManyField(blank=True, to='event.EventPlanerModule'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='basic.Tag'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='basic.Tag'),
        ),
        migrations.AlterField(
            model_name='eventmodulemapper',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='event.AttributeEventModuleMapper'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tags',
            field=models.ManyToManyField(blank=True, to='basic.AbstractAttribute'),
        ),
        migrations.AlterField(
            model_name='registrationparticipant',
            name='eat_habit',
            field=models.ManyToManyField(blank=True, to='basic.EatHabit'),
        ),
        migrations.AlterField(
            model_name='registrationparticipant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='basic.AbstractAttribute'),
        ),
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='other_optional_modules',
            field=models.ManyToManyField(blank=True, related_name='other_optional_modules', to='event.EventModuleMapper'),
        ),
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='other_required_modules',
            field=models.ManyToManyField(blank=True, related_name='other_required_modules', to='event.EventModuleMapper'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='tags',
            field=models.ManyToManyField(to='basic.Tag'),
        ),
    ]
