# Generated by Django 4.0.2 on 2022-03-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_registrationparticipant_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationparticipant',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
