# Generated by Django 4.0.3 on 2022-04-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_workshop_workshopparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
