# Generated by Django 4.0.3 on 2022-03-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_bookingoption_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='standardeventtemplate',
            name='planer_modules',
            field=models.ManyToManyField(blank=True, null=True, to='event.eventplanermodule'),
        ),
    ]
