# Generated by Django 3.2.9 on 2021-12-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20211231_1346'),
        ('event', '0004_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='basic.Tag'),
        ),
    ]
