# Generated by Django 4.0.2 on 2022-03-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_registrationparticipant_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationparticipant',
            name='generated',
            field=models.BooleanField(default=False),
        ),
    ]
