# Generated by Django 4.0.2 on 2022-03-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_event_url_standardeventtemplate_planer_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='planer_modules',
            field=models.ManyToManyField(blank=True, null=True, to='event.EventPlanerModule'),
        ),
    ]
