# Generated by Django 4.0.4 on 2022-06-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_bookingoption_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='can_be_repeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshop',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='workshop',
            name='type',
            field=models.CharField(choices=[('w', 'Workshop'), ('e', 'Excursion'), ('l', 'Vortrag'), ('p', 'Aufführung'), ('d', 'Diskussionsrunde'), ('r', 'Lesung')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='free_text',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
