# Generated by Django 4.0.2 on 2022-03-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_registrationparticipant_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationparticipant',
            name='needs_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
