# Generated by Django 4.0.3 on 2022-03-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_bookingoption_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeeventmodulemapper',
            name='max_entries',
            field=models.IntegerField(default=1),
        ),
    ]
