# Generated by Django 3.2.9 on 2022-01-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20220105_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleepinglocations',
            old_name='additional_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='sleepinglocations',
            name='bookable_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
