# Generated by Django 4.0.2 on 2022-03-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_registrationparticipant_needs_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationparticipant',
            name='needs_confirmation',
            field=models.CharField(choices=[('N', 'Nichts'), ('D', 'Abmelden'), ('A', 'Anmelden')], default='N', max_length=1),
        ),
    ]
