# Generated by Django 4.0.3 on 2022-03-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_standardeventtemplate_planer_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='planer_modules',
            field=models.ManyToManyField(blank=True, to='event.eventplanermodule'),
        ),
    ]
