# Generated by Django 4.0.4 on 2022-06-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_workshop_can_be_repeated_workshop_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
