# Generated by Django 4.0.3 on 2022-03-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_emailattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='event.emailattachment'),
        ),
    ]
