# Generated by Django 3.2.9 on 2022-01-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20211231_1346'),
        ('event', '0007_auto_20220115_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SleepingLocations',
            new_name='SleepingLocation',
        ),
    ]
