# Generated by Django 4.0.4 on 2022-06-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_workshop_price_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationparticipant',
            name='scout_level',
            field=models.CharField(choices=[('N', 'Unbekannt'), ('W', 'Wölfling'), ('S', 'Sippling'), ('R', 'Rover_Innen')], default='N', max_length=6),
        ),
    ]
