# Generated by Django 4.0.2 on 2022-03-24 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_frontendtheme_abstractattribute_in_summary'),
        ('event', '0007_alter_standardeventtemplate_planer_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.frontendtheme'),
        ),
        migrations.AddField(
            model_name='registrationparticipant',
            name='leader',
            field=models.CharField(choices=[('N', 'Kein Amt'), ('StaFue', 'Stammesführung'), ('SiFue', 'Sippenführung'), ('RoFue', 'Roverrundenführung'), ('MeuFue', 'Meutenfürung')], default='N', max_length=6),
        ),
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='planer_modules',
            field=models.ManyToManyField(blank=True, to='event.EventPlanerModule'),
        ),
    ]
