# Generated by Django 4.0.3 on 2022-03-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_rename_end_time_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationparticipant',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationparticipant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
