# Generated by Django 4.0.3 on 2022-03-25 13:04

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_email_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailattachment',
            name='file',
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='html',
            field=models.FileField(blank=True, null=True, storage=backend.storage_backends.EmailAttachmentMediaStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='plain',
            field=models.FileField(blank=True, null=True, storage=backend.storage_backends.EmailAttachmentMediaStorage(), upload_to=''),
        ),
    ]
