# Generated by Django 4.0.3 on 2022-03-25 13:10

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_emailattachment_file_emailattachment_html_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailattachment',
            old_name='html',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='email',
            name='file',
        ),
        migrations.RemoveField(
            model_name='emailattachment',
            name='plain',
        ),
        migrations.AddField(
            model_name='email',
            name='html',
            field=models.FileField(blank=True, null=True, storage=backend.storage_backends.EmailMediaStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='email',
            name='plain',
            field=models.FileField(blank=True, null=True, storage=backend.storage_backends.EmailMediaStorage(), upload_to=''),
        ),
    ]
