# Generated by Django 4.0.4 on 2022-09-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_group_registration_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationparticipant',
            name='allow_permanently',
            field=models.BooleanField(default=False),
        ),
    ]
