# Generated by Django 4.0.3 on 2022-03-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_registrationparticipant_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationparticipant',
            name='needs_confirmation',
            field=models.CharField(choices=[('N', 'Nichts'), ('D', 'Abmelden'), ('AE', 'Anmelden von deaktivierten Teilnehmern'), ('AN', 'Anmelden von neuen Teilnehmern')], default='N', max_length=2),
        ),
    ]
