# Generated by Django 3.2.9 on 2022-01-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20211231_1346'),
        ('event', '0009_alter_sleepinglocation_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.AlterField(
            model_name='sleepinglocation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='basic.Tag'),
        ),
    ]
