# Generated by Django 3.2.9 on 2022-01-30 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('event', '0010_auto_20220116_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='keycloak_admin_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keycloak_admin_group', to='auth.group'),
        ),
        migrations.AddField(
            model_name='registrationparticipant',
            name='sleeping_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.sleepinglocation'),
        ),
        migrations.AddField(
            model_name='sleepinglocation',
            name='bookable_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='keycloak_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keycloak_group', to='auth.group'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='responsible_person',
        ),
        migrations.AddField(
            model_name='event',
            name='responsible_person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
