# Generated by Django 4.0.3 on 2022-03-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_registrationparticipant_needs_confirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributeeventmodulemapper',
            old_name='description',
            new_name='title',
        ),
    ]
