# Generated by Django 4.0.3 on 2022-03-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_rename_html_emailattachment_file_remove_email_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='email',
            name='plain',
            field=models.TextField(default=''),
        ),
    ]
