# Generated by Django 4.0.3 on 2022-03-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_rename_description_attributeeventmodulemapper_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeeventmodulemapper',
            name='text',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
