# Generated by Django 3.2.9 on 2022-01-30 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('basic', '0009_auto_20220130_1215'),
        ('event', '0011_auto_20220130_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractEventModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_event.abstracteventmodule_set+', to='contenttypes.contenttype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.abstractattribute')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='EventModuleSleeping',
            fields=[
                ('abstracteventmodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.abstracteventmodule')),
                ('sleeping_model', models.CharField(choices=[('s', 's'), ('e', 'e')], default='s', max_length=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('event.abstracteventmodule',),
        ),
        migrations.CreateModel(
            name='EventModuleStandard',
            fields=[
                ('abstracteventmodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.abstracteventmodule')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('event.abstracteventmodule',),
        ),
    ]
