# Generated by Django 4.0.3 on 2022-03-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_email_html_alter_email_plain'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitation_code_group',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='invitation_code_single',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
