# Generated by Django 3.2.9 on 2022-01-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_abstracteventmodule_eventmodulesleeping_eventmodulestandard'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='modules',
            field=models.ManyToManyField(to='event.AbstractEventModule'),
        ),
    ]
