# Generated by Django 4.0.1 on 2022-01-30 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_alter_abstractattribute_polymorphic_ctype'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('event', '0013_event_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstracteventmodule',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='abstracteventmodule',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.tagtype'),
        ),
        migrations.AlterField(
            model_name='event',
            name='modules',
            field=models.ManyToManyField(blank=True, null=True, to='event.AbstractEventModule'),
        ),
        migrations.AlterField(
            model_name='eventmodulesleeping',
            name='sleeping_model',
            field=models.CharField(choices=[('s', 'single'), ('e', 'extended')], default='s', max_length=1),
        ),
    ]
