# Generated by Django 4.0.3 on 2022-03-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_services', '0002_email_name'),
        ('event', '0013_remove_email_attachments_delete_emailpicture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='email_services.standardemailregistrationset'),
        ),
    ]
