# Generated by Django 4.0.1 on 2022-01-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_alter_abstracteventmodule_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstracteventmodule',
            name='position',
            field=models.IntegerField(auto_created=True, default=999),
        ),
    ]
