# Generated by Django 4.0.1 on 2022-01-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_abstracteventmodule_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='modules',
            field=models.ManyToManyField(blank=True, to='event.AbstractEventModule'),
        ),
    ]
