# Generated by Django 3.2.9 on 2022-01-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_alter_abstractattribute_polymorphic_ctype'),
        ('event', '0017_alter_event_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModuleMapper',
            fields=[
                ('position', models.IntegerField(auto_created=True, default=999)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.ManyToManyField(to='basic.AbstractAttribute')),
            ],
        ),
        migrations.RemoveField(
            model_name='descriptionregistrationattributerelation',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='descriptionregistrationattributerelation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='descriptionregistrationattributerelation',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='abstracteventmodule',
            name='position',
        ),
        migrations.DeleteModel(
            name='DescriptionEventAttributeRelation',
        ),
        migrations.DeleteModel(
            name='DescriptionRegistrationAttributeRelation',
        ),
        migrations.AlterField(
            model_name='event',
            name='modules',
            field=models.ManyToManyField(blank=True, to='event.EventModuleMapper'),
        ),
    ]
