# Generated by Django 3.2.9 on 2022-01-31 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('basic', '0010_alter_abstractattribute_polymorphic_ctype'),
        ('event', '0018_auto_20220131_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_event.eventmodule_set+', to='contenttypes.contenttype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.tagtype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.DeleteModel(
            name='AbstractEventModule',
        ),
        migrations.DeleteModel(
            name='EventModuleStandard',
        ),
    ]
