# Generated by Django 3.2.9 on 2022-01-31 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_eventmodulemapper_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='modules',
        ),
        migrations.AddField(
            model_name='eventmodulemapper',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
