# Generated by Django 3.2.9 on 2022-01-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_alter_abstractattribute_polymorphic_ctype'),
        ('event', '0021_auto_20220131_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodulemapper',
            name='tags',
            field=models.ManyToManyField(blank=True, to='basic.AbstractAttribute'),
        ),
    ]
