# Generated by Django 3.2.9 on 2022-01-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_alter_eventmodulemapper_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodule',
            name='header',
            field=models.CharField(default='Default Header', max_length=100),
        ),
    ]
