# Generated by Django 3.2.9 on 2022-01-31 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_alter_abstractattribute_polymorphic_ctype'),
        ('event', '0023_eventmodule_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodulemapper',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventmodulemapper',
            name='tags',
        ),
        migrations.AddField(
            model_name='event',
            name='modules',
            field=models.ManyToManyField(blank=True, to='event.EventModuleMapper'),
        ),
        migrations.CreateModel(
            name='AttributeEventModuleMapper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.abstractattribute')),
            ],
        ),
        migrations.AddField(
            model_name='eventmodulemapper',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='event.AttributeEventModuleMapper'),
        ),
    ]
