# Generated by Django 3.2.9 on 2022-01-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_auto_20220131_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodule',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
