# Generated by Django 3.2.9 on 2022-01-31 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_eventmodule_internal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmodule',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventmodule',
            name='polymorphic_ctype',
        ),
    ]
