# Generated by Django 3.2.9 on 2022-02-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_auto_20220131_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='responsible_person',
            new_name='responsible_persons',
        ),
    ]
