# Generated by Django 4.0.2 on 2022-02-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_rename_position_eventmodulemapper_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodule',
            name='description',
        ),
        migrations.AddField(
            model_name='eventmodulemapper',
            name='overwrite_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='eventmodulemapper',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
