# Generated by Django 4.0.2 on 2022-02-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_remove_eventmodule_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodulemapper',
            name='overwrite_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
