# Generated by Django 4.0.2 on 2022-02-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_alter_eventmodulemapper_overwrite_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodule',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
