# Generated by Django 4.0.2 on 2022-02-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_floatattribute_integerattribute'),
        ('event', '0032_eventmodule_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeeventmodulemapper',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='can_register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='basic.scouthierarchy'),
        ),
        migrations.AddField(
            model_name='eventmodulemapper',
            name='standard',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StandardizedModelInstanced',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('standard_confirmation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_confirmation', to='event.eventmodulemapper')),
                ('standard_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_event', to='event.event')),
                ('standard_group_registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_group_registration', to='event.eventmodulemapper')),
                ('standard_introduction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_introduction', to='event.eventmodulemapper')),
                ('standard_personal_registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_personal_registration', to='event.eventmodulemapper')),
            ],
        ),
    ]
