# Generated by Django 4.0.2 on 2022-02-26 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_attributeeventmodulemapper_is_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardEventInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('confirmation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmation', to='event.eventmodulemapper')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='event.event')),
                ('group_registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_registration', to='event.eventmodulemapper')),
                ('introduction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduction', to='event.eventmodulemapper')),
                ('personal_registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_registration', to='event.eventmodulemapper')),
            ],
        ),
        migrations.DeleteModel(
            name='StandardizedModelInstanced',
        ),
    ]
