# Generated by Django 4.0.2 on 2022-02-26 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_alter_scouthierarchy_level_and_more'),
        ('event', '0034_standardeventinstance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='scout_hierachy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.scouthierarchy'),
        ),
        migrations.AlterField(
            model_name='registrationparticipant',
            name='scout_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.scouthierarchy'),
        ),
    ]
