# Generated by Django 4.0.2 on 2022-02-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_alter_scouthierarchy_level_and_more'),
        ('event', '0035_alter_registration_scout_hierachy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='can_register',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.scouthierarchy'),
        ),
    ]
