# Generated by Django 4.0.2 on 2022-02-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_alter_scouthierarchy_level_and_more'),
        ('event', '0036_alter_event_can_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='can_register',
            field=models.ForeignKey(default=493, on_delete=django.db.models.deletion.SET_DEFAULT, to='basic.scouthierarchy'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='scout_hierachy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.scouthierarchy'),
        ),
        migrations.AlterField(
            model_name='registrationparticipant',
            name='scout_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.scouthierarchy'),
        ),
    ]
