# Generated by Django 4.0.2 on 2022-02-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0037_alter_event_can_register_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardeventinstance',
            name='other_modules',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_modules', to='event.EventModuleMapper'),
        ),
    ]
