# Generated by Django 4.0.2 on 2022-02-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_standardeventinstance_other_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardeventinstance',
            name='other_modules',
            field=models.ManyToManyField(blank=True, related_name='other_modules', to='event.EventModuleMapper'),
        ),
    ]
