# Generated by Django 4.0.2 on 2022-02-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0019_travelattribute'),
        ('event', '0040_standardeventinstance_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='can_register',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_model',
        ),
        migrations.AddField(
            model_name='event',
            name='group_registraion',
            field=models.CharField(choices=[('N', 'No'), ('O', 'Optional'), ('R', 'Required')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='limited_registration_hierarchy',
            field=models.ForeignKey(default=493, on_delete=django.db.models.deletion.SET_DEFAULT, to='basic.scouthierarchy'),
        ),
        migrations.AddField(
            model_name='event',
            name='personal_data_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='single_registration',
            field=models.BooleanField(default=False),
        ),
    ]
