# Generated by Django 4.0.2 on 2022-02-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0041_remove_event_can_register_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='group_registraion',
            new_name='group_registration',
        ),
        migrations.AddField(
            model_name='registration',
            name='personal',
            field=models.BooleanField(default=False),
        ),
    ]
