# Generated by Django 4.0.2 on 2022-02-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0043_rename_standardeventinstance_standardeventtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardeventtemplate',
            old_name='group_registration',
            new_name='registration',
        ),
    ]
