# Generated by Django 4.0.2 on 2022-02-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0044_rename_group_registration_standardeventtemplate_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardeventtemplate',
            old_name='confirmation',
            new_name='summary',
        ),
    ]
