# Generated by Django 4.0.2 on 2022-02-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0045_rename_confirmation_standardeventtemplate_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardeventtemplate',
            name='other_modules',
        ),
        migrations.AddField(
            model_name='standardeventtemplate',
            name='other_optional_modules',
            field=models.ManyToManyField(blank=True, related_name='other_optional_modules', to='event.EventModuleMapper'),
        ),
        migrations.AddField(
            model_name='standardeventtemplate',
            name='other_required_modules',
            field=models.ManyToManyField(blank=True, related_name='other_required_modules', to='event.EventModuleMapper'),
        ),
    ]
