# Generated by Django 4.0.2 on 2022-03-02 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0047_alter_event_single_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodulemapper',
            name='event',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AlterField(
            model_name='eventmodulemapper',
            name='module',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='event.eventmodule'),
        ),
    ]
