# Generated by Django 4.0.2 on 2022-03-02 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0048_alter_eventmodulemapper_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodulemapper',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AlterField(
            model_name='eventmodulemapper',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.eventmodule'),
        ),
    ]
