# Generated by Django 4.0.2 on 2022-03-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0019_travelattribute'),
        ('event', '0049_alter_eventmodulemapper_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='personal',
        ),
        migrations.AlterField(
            model_name='registration',
            name='tags',
            field=models.ManyToManyField(to='basic.AbstractAttribute'),
        ),
        migrations.AlterField(
            model_name='registrationparticipant',
            name='tags',
            field=models.ManyToManyField(to='basic.AbstractAttribute'),
        ),
    ]
