# Generated by Django 4.0.2 on 2022-03-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0050_remove_registration_personal_alter_registration_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='personal',
            field=models.BooleanField(default=False),
        ),
    ]
