# Generated by Django 4.0.2 on 2022-03-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0051_registration_personal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='personal',
            new_name='single',
        ),
        migrations.AddField(
            model_name='event',
            name='long_description',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
