# Generated by Django 4.0.4 on 2022-05-09 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0004_event_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('transfer_subject', models.CharField(blank=True, max_length=250)),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
                ('transfer_reference_id', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.registration')),
                ('transfer_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
