# Generated by Django 4.0.4 on 2022-05-19 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0005_bookingoption_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileGenereted',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(upload_to='')),
                ('error_msg', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('Q', 'In der Warteschlange.'), ('P', 'Dokument wird erstellt.'), ('FS', 'Dokument erfolgreich erstellt.'), ('FF', 'Dokumenten Erstellung Fehlgeschlagen.')], default='Q', max_length=2)),
                ('type', models.CharField(choices=[('KE', 'KJP Excel Datei.'), ('P', 'KJP PDF Datei.'), ('PLE', 'Teilnehmerliste Excel.'), ('PLP', 'Teilnehmerliste PDF.')], default='KE', max_length=3)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
