# Generated by Django 4.0.4 on 2022-05-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filegenereted',
            name='extension',
            field=models.CharField(choices=[('E', 'Excel'), ('P', 'PDF')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='filegenereted',
            name='type',
            field=models.CharField(choices=[('K', 'KJP Liste'), ('P', 'Teilnehmerliste')], default='K', max_length=1),
        ),
    ]
