# Generated by Django 4.0.4 on 2022-05-20 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_generator', '0002_filegenereted_extension_alter_filegenereted_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTemplate',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('type', models.CharField(choices=[('K', 'KJP Liste'), ('P', 'Teilnehmerliste')], default='K', max_length=1)),
                ('extension', models.CharField(choices=[('E', 'Excel'), ('P', 'PDF')], default='E', max_length=1)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
    ]
