# Generated by Django 4.0.4 on 2022-05-20 16:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0005_bookingoption_end_date_and_more'),
        ('file_generator', '0003_filetemplate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileGenereted',
            new_name='GeneratedFiles',
        ),
    ]
