# Generated by Django 4.0.4 on 2022-05-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_generator', '0006_alter_filetemplate_file_alter_generatedfiles_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedfiles',
            name='template_version',
            field=models.IntegerField(default=1),
        ),
    ]
