# Generated by Django 4.0.4 on 2022-05-26 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_generator', '0007_generatedfiles_template_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedfiles',
            name='template_version',
        ),
        migrations.RemoveField(
            model_name='generatedfiles',
            name='type',
        ),
        migrations.AddField(
            model_name='generatedfiles',
            name='file_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_generator.filetemplate'),
        ),
    ]
