# Generated by Django 4.0.4 on 2022-05-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_generator', '0008_remove_generatedfiles_template_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedfiles',
            old_name='file_template',
            new_name='template',
        ),
    ]
