# Generated by Django 4.1 on 2022-08-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_generator', '0011_alter_filetemplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetemplate',
            name='type',
            field=models.CharField(choices=[('K', 'KJP Liste'), ('I', 'Rechnungserstellung Felix'), ('P', 'Teilnehmerliste'), ('A', 'Attributliste'), ('T', 'Anreise Matrix')], default='K', max_length=1),
        ),
    ]
