# Generated by Django 4.1 on 2022-09-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_generator', '0012_alter_filetemplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedfiles',
            name='error_msg',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
