# Generated by Django 4.0.3 on 2022-03-28 21:25

import backend.storage_backends
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=60, null=True)),
                ('html', models.TextField(default='')),
                ('plain', models.TextField(default='')),
                ('type', models.CharField(choices=[('StandardEmail', 'Allgemeine Email'), ('EventCreated', 'Event erstellt'), ('EventUpdated', 'Event verändert'), ('RegistrationCreated', 'Registrierung erstellt'), ('RegistrationUpdated', 'Registrierung verändert'), ('RegistrationReminder', 'Bestätigungs errinerung'), ('RegistrationAccepted', 'Registrierungsbestätigung')], default='StandardEmail', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, null=True, storage=backend.storage_backends.EmailAttachmentMediaStorage(), upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailPicture',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.ImageField(storage=backend.storage_backends.PublicMediaStorage(), upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardEmailSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('event_created', models.ForeignKey(limit_choices_to={'type': 'EventCreated'}, on_delete=django.db.models.deletion.PROTECT, related_name='event_created', to='email_services.email')),
                ('event_updated', models.ForeignKey(limit_choices_to={'type': 'EventUpdated'}, on_delete=django.db.models.deletion.PROTECT, related_name='event_updated', to='email_services.email')),
                ('standard_email', models.ForeignKey(limit_choices_to={'type': 'StandardEmail'}, on_delete=django.db.models.deletion.PROTECT, related_name='standard_email', to='email_services.email')),
            ],
        ),
        migrations.CreateModel(
            name='StandardEmailRegistrationSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('registration_accepted', models.ForeignKey(limit_choices_to={'type': 'RegistrationAccepted'}, on_delete=django.db.models.deletion.PROTECT, related_name='registration_accepted', to='email_services.email')),
                ('registration_created', models.ForeignKey(limit_choices_to={'type': 'RegistrationCreated'}, on_delete=django.db.models.deletion.PROTECT, related_name='registration_created', to='email_services.email')),
                ('registration_reminder', models.ForeignKey(limit_choices_to={'type': 'RegistrationReminder'}, on_delete=django.db.models.deletion.PROTECT, related_name='registration_reminder', to='email_services.email')),
                ('registration_updated', models.ForeignKey(limit_choices_to={'type': 'RegistrationUpdated'}, on_delete=django.db.models.deletion.PROTECT, related_name='registration_updated', to='email_services.email')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='email_services.emailattachment'),
        ),
    ]
