# Generated by Django 4.0.3 on 2022-03-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
