# Generated by Django 4.1 on 2022-08-15 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardemailregistrationset',
            name='payment_reminder',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'PaymentReminder'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_reminder', to='email_services.email'),
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('StandardEmail', 'Allgemeine Email'), ('EventCreated', 'Event erstellt'), ('EventUpdated', 'Event verändert'), ('RegistrationCreated', 'Registrierung erstellt'), ('RegistrationUpdated', 'Registrierung verändert'), ('RegistrationReminder', 'Bestätigungs errinerung'), ('RegistrationAccepted', 'Registrierungsbestätigung'), ('PaymentReminder', 'Bezahlungserrinnerung')], default='StandardEmail', max_length=20),
        ),
        migrations.AlterField(
            model_name='standardemailregistrationset',
            name='registration_accepted',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'RegistrationAccepted'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_accepted', to='email_services.email'),
        ),
        migrations.AlterField(
            model_name='standardemailregistrationset',
            name='registration_created',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'RegistrationCreated'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_created', to='email_services.email'),
        ),
        migrations.AlterField(
            model_name='standardemailregistrationset',
            name='registration_reminder',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'RegistrationReminder'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_reminder', to='email_services.email'),
        ),
        migrations.AlterField(
            model_name='standardemailregistrationset',
            name='registration_updated',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'RegistrationUpdated'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_updated', to='email_services.email'),
        ),
    ]
