# Generated by Django 4.0.6 on 2022-09-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_services', '0002_standardemailregistrationset_payment_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardemailregistrationset',
            name='custom_mail',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'StandardEmail'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_mail', to='email_services.email'),
        ),
    ]
