# Generated by Django 4.1.2 on 2022-12-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_services', '0003_standardemailregistrationset_custom_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailpicture',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
