# Generated by Django 4.1.4 on 2022-12-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_services', '0004_emailpicture_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardemailregistrationset',
            name='registration_accepted',
        ),
        migrations.RemoveField(
            model_name='standardemailregistrationset',
            name='registration_reminder',
        ),
        migrations.RemoveField(
            model_name='standardemailregistrationset',
            name='registration_updated',
        ),
    ]
