# Generated by Django 3.1.4 on 2020-12-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('zipCode', models.CharField(blank=True, max_length=5)),
                ('address', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutOrgaLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutHerarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('zipCode', models.CharField(blank=True, max_length=5)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.scoutorgalevel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoutherarchy', to='basic.scoutherarchy')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfParticipants', models.IntegerField()),
                ('responsiblePerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.person')),
                ('scoutOrganisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.scoutherarchy')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='scoutOrganisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.scoutherarchy'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('registrationDeadline', models.DateTimeField(blank=True, null=True)),
                ('registrationStart', models.DateTimeField(blank=True, null=True)),
                ('participationFee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('minHelper', models.IntegerField(blank=True, null=True)),
                ('minParticipation', models.IntegerField(blank=True, null=True)),
                ('maxParticipation', models.IntegerField(blank=True, null=True)),
                ('ageGroups', models.ManyToManyField(blank=True, to='basic.AgeGroup')),
                ('contacts', models.ManyToManyField(blank=True, to='basic.Person')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.eventlocation')),
            ],
        ),
    ]
