# Generated by Django 3.1.4 on 2021-01-06 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='responsible_persons',
        ),
        migrations.AddField(
            model_name='registration',
            name='responsible_persons',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
