# Generated by Django 3.1.4 on 2020-12-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='caro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
