# Generated by Django 3.1.4 on 2021-01-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlocation',
            old_name='capacity',
            new_name='capacity_indoor',
        ),
        migrations.AddField(
            model_name='agegroup',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='capacity_outdoor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eathabittype',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
