# Generated by Django 3.1.5 on 2021-02-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postaladdress',
            old_name='addressAddition',
            new_name='address_addition',
        ),
    ]
