# Generated by Django 4.0.3 on 2022-03-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractattribute',
            name='description',
        ),
    ]
