# Generated by Django 4.0.3 on 2022-03-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='answer',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='question',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
