# Generated by Django 3.1.4 on 2021-02-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantpersonal',
            name='scout_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
