# Generated by Django 3.1.4 on 2021-01-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20210118_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantpersonal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='free_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
