# Generated by Django 4.0.4 on 2022-05-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_messagetype_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringattribute',
            name='string_field',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
