# Generated by Django 3.2.9 on 2021-11-28 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_rename_tagtime_timeattribute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DescriptionTagRelation',
            new_name='DescriptionEventAttributeRelation',
        ),
        migrations.AddField(
            model_name='abstractattribute',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='keycloak_path',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='tags',
            field=models.ManyToManyField(to='basic.Tag'),
        ),
        migrations.AddField(
            model_name='registrationparticipant',
            name='tags',
            field=models.ManyToManyField(to='basic.Tag'),
        ),
        migrations.AddField(
            model_name='sleepinglocations',
            name='tags',
            field=models.ManyToManyField(to='basic.Tag'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='tags',
            field=models.ManyToManyField(to='basic.Tag'),
        ),
        migrations.CreateModel(
            name='DescriptionRegistrationAttributeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.abstractattribute')),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.attributedescription')),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.registration')),
            ],
        ),
    ]
