# Generated by Django 4.0.3 on 2022-03-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_abstractattribute_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractattribute',
            name='template_id',
            field=models.IntegerField(default=-1),
        ),
    ]
