# Generated by Django 3.1.5 on 2021-02-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20210228_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
