# Generated by Django 3.1.4 on 2020-12-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_agegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='caro',
        ),
    ]
