# Generated by Django 4.0.3 on 2022-03-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_eathabit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eathabit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
