# Generated by Django 3.1.5 on 2021-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20210228_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='free_text',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
