# Generated by Django 4.0.4 on 2022-05-18 19:46
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('basic', '0003_alter_stringattribute_string_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcode',
            name='state',
            field=models.CharField(
                choices=[('BW', 'Baden-Württemberg'), ('BY', 'Bayern'), ('BE', 'Berlin'), ('BB', 'Brandenburg'),
                         ('HB', 'Bremen'), ('HH', 'Hamburg'), ('HE', 'Hessen'), ('MV', 'Mecklenburg-Vorpommern'),
                         ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'),
                         ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('SH', 'Schleswig-Holstein'),
                         ('TH', 'Thüringen')], default='BY', max_length=2),
        ),
    ]
