# Generated by Django 4.0.3 on 2022-05-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_alter_stringattribute_string_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='internal_comment',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
