# Generated by Django 3.2.9 on 2021-11-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20211128_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='basic.Tag'),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='tags',
            field=models.ManyToManyField(to='basic.Tag'),
        ),
    ]
