# Generated by Django 4.0.3 on 2022-03-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_alter_abstractattribute_template_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('answer', models.CharField(blank=True, max_length=10000, null=True)),
                ('type', models.CharField(choices=[('FAQ', 'FAQ'), ('P', 'Datenschutz'), ('LN', 'Impressum')], default='FAQ', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
