# Generated by Django 4.0.4 on 2022-05-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_message_internal_comment'),
        ('basic', '0004_zipcode_state'),
    ]

    operations = [
    ]
