# Generated by Django 3.1.5 on 2021-03-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20210306_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
