# Generated by Django 3.2.9 on 2021-11-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20211128_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractattribute',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
