# Generated by Django 4.0.3 on 2022-03-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_alter_eathabit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelattribute',
            name='time_field',
            field=models.CharField(blank=True, choices=[('B', 'Früher'), ('E', '16:00-18:00'), ('N', '18:00-20:00'), ('L', '20:00-22:00'), ('SL', '22:00-24:00'), ('O', 'Noch Später')], max_length=2, null=True),
        ),
    ]
