# Generated by Django 4.0.3 on 2022-03-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractattribute',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.tagtype'),
        ),
    ]
