# Generated by Django 4.0.3 on 2022-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_alter_travelattribute_time_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='type',
            field=models.CharField(choices=[('FAQ', 'FAQ'), ('P', 'Datenschutz')], default='FAQ', max_length=3),
        ),
    ]
