# Generated by Django 3.1.5 on 2021-03-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_event_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtag',
            name='email_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
