# Generated by Django 3.2.9 on 2021-11-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_abstractattribute_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_model',
            field=models.CharField(choices=[('SO', 'Single Only'), ('GO', 'Groups Only'), ('GOSO', 'Groups Optional, Single Optional'), ('GRSO', 'Groups Required Single Optional')], default='GO', max_length=4),
        ),
    ]
