# Generated by Django 4.0.4 on 2022-06-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_merge_20220527_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutHierarchyChildModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('childs', models.ManyToManyField(blank=True, related_name='childs', to='basic.scouthierarchy')),
                ('head', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head', to='basic.scouthierarchy')),
            ],
        ),
    ]
