# Generated by Django 4.0.4 on 2022-06-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_scouthierarchychildmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoutHierarchyChildModel',
        ),
    ]
