# Generated by Django 3.2.3 on 2021-06-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_registrationmatching_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmatching',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.event'),
        ),
    ]
