# Generated by Django 4.0.2 on 2022-03-24 11:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_alter_description_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=100)),
                ('primary', colorfield.fields.ColorField(default='#1976D2', image_field=None, max_length=18, samples=None)),
                ('secondary', colorfield.fields.ColorField(default='#424242', image_field=None, max_length=18, samples=None)),
                ('accent', colorfield.fields.ColorField(default='#82B1FF', image_field=None, max_length=18, samples=None)),
                ('error', colorfield.fields.ColorField(default='#FF5252', image_field=None, max_length=18, samples=None)),
                ('info', colorfield.fields.ColorField(default='#2196F3', image_field=None, max_length=18, samples=None)),
                ('success', colorfield.fields.ColorField(default='#4CAF50', image_field=None, max_length=18, samples=None)),
                ('warning', colorfield.fields.ColorField(default='#FFC107', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.AddField(
            model_name='abstractattribute',
            name='in_summary',
            field=models.BooleanField(default=True),
        ),
    ]
