# Generated by Django 3.2.3 on 2021-06-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_registrationmatching_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmatching',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationmatching',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
