# Generated by Django 4.0.4 on 2022-06-18 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_delete_scouthierarchychildmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAttributeV2',
            fields=[
                ('abstractattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basic.abstractattribute')),
                ('number_persons', models.IntegerField(default=0)),
                ('type_field', models.CharField(blank=True, choices=[('T', 'Bahn'), ('B', 'Reisebus'), ('C', 'PKW'), ('O', 'Sonstiges')], max_length=1, null=True)),
                ('date_time_field', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('basic.abstractattribute',),
        ),
    ]
