# Generated by Django 3.2.3 on 2021-06-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20210623_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationmatching',
            old_name='place',
            new_name='sleeping_location',
        ),
        migrations.AddField(
            model_name='registrationmatching',
            name='event_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.zipcode'),
        ),
    ]
