# Generated by Django 3.2.4 on 2021-07-21 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_auto_20210624_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrole',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('free_text', models.CharField(blank=True, max_length=1000)),
                ('costs', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.registration')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.participantpersonal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
