# Generated by Django 3.2.4 on 2021-07-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_auto_20210721_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
