# Generated by Django 4.0.2 on 2022-02-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_alter_abstractattribute_polymorphic_ctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatAttribute',
            fields=[
                ('abstractattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basic.abstractattribute')),
                ('float_field', models.FloatField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('basic.abstractattribute',),
        ),
        migrations.CreateModel(
            name='IntegerAttribute',
            fields=[
                ('abstractattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basic.abstractattribute')),
                ('integer_field', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('basic.abstractattribute',),
        ),
    ]
