# Generated by Django 4.0.2 on 2022-02-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_floatattribute_integerattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scouthierarchy',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scouthierarchy', to='basic.scouthierarchy'),
        ),
    ]
