# Generated by Django 3.1.7 on 2021-07-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_alter_workshop_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantpersonal',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='participantpersonal',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='participantpersonal',
            name='scout_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
