# Generated by Django 4.0.2 on 2022-02-26 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_alter_scouthierarchy_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scouthierarchy',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.scoutorgalevel'),
        ),
        migrations.AlterField(
            model_name='scouthierarchy',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scouthierarchy', to='basic.scouthierarchy'),
        ),
    ]
