# Generated by Django 3.2.5 on 2021-11-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_personal_registration',
            field=models.BooleanField(default=0),
        ),
    ]
