# Generated by Django 3.2.5 on 2021-11-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0014_event_is_personal_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='max_person',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='min_person',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
