# Generated by Django 4.0.2 on 2022-02-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0014_alter_scouthierarchy_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scouthierarchy',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.scoutorgalevel'),
        ),
        migrations.AlterField(
            model_name='scouthierarchy',
            name='zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.zipcode'),
        ),
    ]
