# Generated by Django 3.2.9 on 2021-11-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_auto_20211110_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouthierarchy',
            name='abbreviation',
            field=models.CharField(default='DPBM', max_length=5),
        ),
    ]
