# Generated by Django 4.0.2 on 2022-02-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_alter_scouthierarchy_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scouthierarchy',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.scoutorgalevel'),
        ),
        migrations.AlterField(
            model_name='scouthierarchy',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scouthierarchy', to='basic.scouthierarchy'),
        ),
        migrations.AlterField(
            model_name='scouthierarchy',
            name='zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.zipcode'),
        ),
    ]
