# Generated by Django 3.2.9 on 2021-11-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_scouthierarchy_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scouthierarchy',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
