# Generated by Django 3.2.5 on 2022-02-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_alter_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantpersonal',
            name='is_group_leader',
        ),
        migrations.RemoveField(
            model_name='participantpersonal',
            name='scout_group',
        ),
        migrations.AddField(
            model_name='participantpersonal',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
