# Generated by Django 4.0.2 on 2022-02-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_alter_scouthierarchy_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoIntegerAttribute',
            fields=[
                ('abstractattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basic.abstractattribute')),
                ('intege_one_field', models.IntegerField()),
                ('integer_two_field', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('basic.abstractattribute',),
        ),
    ]
