# Generated by Django 4.0.2 on 2022-02-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0017_twointegerattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integerattribute',
            name='integer_field',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TwoIntegerAttribute',
        ),
    ]
