# Generated by Django 4.0.2 on 2022-02-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0018_alter_integerattribute_integer_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAttribute',
            fields=[
                ('abstractattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basic.abstractattribute')),
                ('type_field', models.CharField(blank=True, choices=[('T', 'Bahn'), ('B', 'Reisebus'), ('C', 'PKW'), ('O', 'Sonstiges')], max_length=1, null=True)),
                ('time_field', models.CharField(blank=True, choices=[('E', '16:00-18:00'), ('N', '18:00-20:00'), ('L', '20:00-22:00'), ('SL', '22:00-24:00'), ('O', 'Noch Später')], max_length=2, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('basic.abstractattribute',),
        ),
    ]
