# Generated by Django 3.1.4 on 2021-01-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anmeldung_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextended',
            old_name='mobile_mumber',
            new_name='mobile_number',
        ),
    ]
